# airの設定ファイル
# 詳細: https://github.com/cosmtrek/air

root = "."
tmp_dir = "tmp"

[build]
# バイナリを配置するフォルダ
bin = "./tmp/main"
# メインのGoファイル
cmd = "go build -o ./tmp/main ./cmd/server"
# 監視するファイル拡張子
include_ext = ["go", "tpl", "tmpl", "html"]
# 除外するディレクトリ
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules", "build"]
# 除外するファイル
exclude_file = []
# プロジェクトのルートディレクトリ停止時にtmpディレクトリを削除
clean_on_exit = true
# 環境変数の設定
env = []

[log]
# デバッグモード表示
time = true

[color]
# カラー出力の設定
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# 監視間隔（ミリ秒）
clean_on_exit = true 